# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

# Importing Data

In [2]:
path=r"C:\Users\suhas\Documents\cf\Instacart Data Analysis"

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_updated.pkl'))

# STEP2

In [3]:
# creat subset
ords_prods_merge_sub=ords_prods_merge[:1000000]
ords_prods_merge_sub.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,customers_current_order_count,order_days_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,7.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders

In [4]:
ords_prods_merge_sub.groupby(['department_id']).agg({'order_id':['mean']})

                   order_id
                       mean
department_id
1              1.714093e+06
2              1.774713e+06
3              1.710320e+06
4              1.712566e+06
5              1.696550e+06
6              1.700705e+06
7              1.715176e+06
8              1.708883e+06
9              1.708130e+06
10             1.714901e+06
11             1.715562e+06
12             1.704916e+06
13             1.710967e+06
14             1.708544e+06
15             1.706717e+06
16             1.707790e+06
17             1.710780e+06
18             1.711857e+06
19             1.711624e+06
20             1.703167e+06
21             1.708208e+06

In [5]:
# Use groupby and agg functions to calculate mean of user_order_id
ords_prods_merge.groupby(['department_id']).agg({'order_id':['mean']})

                   order_id
                       mean
department_id
1              1.711355e+06
2              1.715933e+06
3              1.710699e+06
4              1.710657e+06
5              1.712457e+06
6              1.707786e+06
7              1.711079e+06
8              1.713301e+06
9              1.711269e+06
10             1.717443e+06
11             1.711377e+06
12             1.712768e+06
13             1.711952e+06
14             1.709313e+06
15             1.712026e+06
16             1.710331e+06
17             1.711255e+06
18             1.706348e+06
19             1.710089e+06
20             1.709579e+06
21             1.718715e+06

# STEP3

There are 21 depatment_id's compared to the subset of 100000 there are only 8. And the mean order numbers seem to be different for each department when looking at the entire data frame.

# STEP4

In [6]:
# Creating new column "max_order"
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_id'].transform(np.max)

C:\Users\suhas\AppData\Local\Temp\ipykernel_3156\2493090392.py:2: FutureWarning: The provided callable <function max at 0x000001B00E9867A0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_id'].transform(np.max)

In [7]:
# Checking for new column
ords_prods_merge.head(20)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,customers_current_order_count,order_days_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3160996
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3160996
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,2322397
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,7.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,1813452
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,1813452
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,3412491
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,2724496
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3297166
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,3172001
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,3172001
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,11,7.0,1,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,2925011
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,13,7.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3356003
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,13,7.0,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,3356003
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3356003
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,10,2.0,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3171753
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,prior,7,2,8,6.0,18,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3171753
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,prior,9,5,8,10.0,12,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3171753
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,prior,4,2,0,7.0,10,0,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,3291763
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,prior,5,1,21,6.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,3291763
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,prior,6,1,0,14.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,3291763

In [8]:
# Assign loyalty flag
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [9]:
# Check loyalty flags
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Loyal customer    32404859
Name: count, dtype: int64

In [10]:
# Check Loyalty flag in dataframe
ords_prods_merge[['user_id', 'loyalty_flag', 'order_id','max_order']].head(20)

    user_id    loyalty_flag  order_id  max_order
0       138  Loyal customer   3139998    3160996
1       138  Loyal customer   1977647    3160996
2       709  Loyal customer    389851    2322397
3       764  Loyal customer    652770    1813452
4       764  Loyal customer   1813452    1813452
5       777  Loyal customer   1701441    3412491
6       825  Loyal customer   1871483    2724496
7       910  Loyal customer   1290456    3297166
8      1052  Loyal customer    369558    3172001
9      1052  Loyal customer    589712    3172001
10     1379  Loyal customer   1798115    2925011
11     1480  Loyal customer    497193    3356003
12     1480  Loyal customer   1727826    3356003
13     1480  Loyal customer   2694698    3356003
14     1494  Loyal customer   3171753    3171753
15     1494  Loyal customer    186761    3171753
16     1494  Loyal customer    317121    3171753
17     1540  Loyal customer    200390    3291763
18     1540  Loyal customer    374436    3291763
19     1540  Loyal customer   2920553    3291763

# STEP5

In [11]:
# the min max and mean of each loyalty flag
ords_prods_merge.groupby(['loyalty_flag']).agg({'prices':['mean','min','max']})

                   prices
                     mean  min      max
loyalty_flag
Loyal customer  11.980226  1.0  99999.0

New customers have the least price of products in both the average and max. Loyal customer have the highest price of products in both the average and max.

# STEP6

In [12]:
# Creating column for average spender
ords_prods_merge['average_spend']=ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

C:\Users\suhas\AppData\Local\Temp\ipykernel_3156\655122787.py:2: FutureWarning: The provided callable <function mean at 0x000001B00E9871A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merge['average_spend']=ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [13]:
# Creating flag for low and high spender
ords_prods_merge.loc[ords_prods_merge['average_spend']<10,'spender_flag']='Low_spender'

ords_prods_merge.loc[ords_prods_merge['average_spend']>= 10, 'spender_flag'] = 'High_spender'

In [14]:
# Check spender flags
ords_prods_merge['spender_flag'].value_counts(dropna = False)

spender_flag
Low_spender     31770614
High_spender      634245
Name: count, dtype: int64

In [15]:
pd.options.display.max_rows = 100

In [16]:
ords_prods_merge[['user_id', 'average_spend', 'spender_flag', 'prices']].head(100)

    user_id  average_spend  spender_flag  prices
0       138       6.935811   Low_spender     5.8
1       138       6.935811   Low_spender     5.8
2       709       7.930208   Low_spender     5.8
3       764       4.972414   Low_spender     5.8
4       764       4.972414   Low_spender     5.8
5       777       6.935398   Low_spender     5.8
6       825       5.957576   Low_spender     5.8
7       910       6.680000   Low_spender     5.8
8      1052       7.162500   Low_spender     5.8
9      1052       7.162500   Low_spender     5.8
10     1379       5.813636   Low_spender     5.8
11     1480       5.081633   Low_spender     5.8
12     1480       5.081633   Low_spender     5.8
13     1480       5.081633   Low_spender     5.8
14     1494       6.803797   Low_spender     5.8
15     1494       6.803797   Low_spender     5.8
16     1494       6.803797   Low_spender     5.8
17     1540       6.607122   Low_spender     5.8
18     1540       6.607122   Low_spender     5.8
19     1540       6.607122   Low_spender     5.8
20     1540       6.607122   Low_spender     5.8
21     1540       6.607122   Low_spender     5.8
22     1540       6.607122   Low_spender     5.8
23     1540       6.607122   Low_spender     5.8
24     1540       6.607122   Low_spender     5.8
25     1540       6.607122   Low_spender     5.8
26     1540       6.607122   Low_spender     5.8
27     1540       6.607122   Low_spender     5.8
28     1540       6.607122   Low_spender     5.8
29     1540       6.607122   Low_spender     5.8
30     1540       6.607122   Low_spender     5.8
31     1540       6.607122   Low_spender     5.8
32     1540       6.607122   Low_spender     5.8
33     1540       6.607122   Low_spender     5.8
34     1598       7.123529   Low_spender     5.8
35     1598       7.123529   Low_spender     5.8
36     1598       7.123529   Low_spender     5.8
37     1647       4.853521   Low_spender     5.8
38     1647       4.853521   Low_spender     5.8
39     1647       4.853521   Low_spender     5.8
40     1647       4.853521   Low_spender     5.8
41     1647       4.853521   Low_spender     5.8
42     2833       7.377143   Low_spender     5.8
43     2850       8.054153   Low_spender     5.8
44     2857       8.353793   Low_spender     5.8
45     3010       6.452800   Low_spender     5.8
46     3029       7.960606   Low_spender     5.8
47     3395       6.322222   Low_spender     5.8
48     3904       7.511111   Low_spender     5.8
49     4006       7.441100   Low_spender     5.8
50     4006       7.441100   Low_spender     5.8
51     4006       7.441100   Low_spender     5.8
52     4006       7.441100   Low_spender     5.8
53     4006       7.441100   Low_spender     5.8
54     4122       7.598765   Low_spender     5.8
55     4141       6.033333   Low_spender     5.8
56     4343       7.393939   Low_spender     5.8
57     4553       5.715789   Low_spender     5.8
58     4845       7.229630   Low_spender     5.8
59     6866       4.807143   Low_spender     5.8
60     7275       4.620833   Low_spender     5.8
61     7669       9.106757   Low_spender     5.8
62     7669       9.106757   Low_spender     5.8
63     7669       9.106757   Low_spender     5.8
64     7981       7.115714   Low_spender     5.8
65     7981       7.115714   Low_spender     5.8
66     7981       7.115714   Low_spender     5.8
67     7981       7.115714   Low_spender     5.8
68     7981       7.115714   Low_spender     5.8
69     8703       6.593459   Low_spender     5.8
70     8723       5.677397   Low_spender     5.8
71     8735       5.850000   Low_spender     5.8
72     9293      11.857143  High_spender     5.8
73     9293      11.857143  High_spender     5.8
74     9467       7.709091   Low_spender     5.8
75     9694       7.075354   Low_spender     5.8
76     9694       7.075354   Low_spender     5.8
77     9694       7.075354   Low_spender     5.8
78     9694       7.075354   Low_spender     5.8
79     9694       7.075354   Low_spender     5.8
80     9694       7.075354   Low_spender     5.8
81     9694       7.075354   Low_spender     5.8
82     9694       7.075354   Low_spender     5.8
83     9694       7.075354   Low_spender     5.8
84     9694       7.075354   Low_spender     5.8
85     9694       7.075354   Low_spender     5.8
86     9848       8.312203   Low_spender     5.8
87    10113       8.769565   Low_spender     5.8
88    10315      10.188889  High_spender     5.8
89    10479       7.779775   Low_spender     5.8
90    10708       7.777403   Low_spender     5.8
91    10708       7.777403   Low_spender     5.8
92    10789       6.097701   Low_spender     5.8
93    10789       6.097701   Low_spender     5.8
94    10789       6.097701   Low_spender     5.8
95    10831       7.494286   Low_spender     5.8
96    11119       5.878641   Low_spender     5.8
97    11186       6.618085   Low_spender     5.8
98    11243       5.927149   Low_spender     5.8
99    11448       5.981250   Low_spender     5.8

# STEP7

In [17]:
# Create a column for frequet users
ords_prods_merge['Customer_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

C:\Users\suhas\AppData\Local\Temp\ipykernel_3156\3165240341.py:2: FutureWarning: The provided callable <function median at 0x000001B00EAC3100> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merge['Customer_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [18]:
# Creating flag on order frequency
ords_prods_merge.loc[ords_prods_merge['Customer_frequency'] > 20, 'frequency_flag'] = 'Non_frequent_customer'

ords_prods_merge.loc[(ords_prods_merge['Customer_frequency']>10) & (ords_prods_merge['Customer_frequency']<=20),'frequency_flag'] = 'Regular customer'

ords_prods_merge.loc[ords_prods_merge['Customer_frequency'] <= 10, 'frequency_flag'] = 'Frequent Customer'

In [19]:
# Check frequency flags

ords_prods_merge['frequency_flag'].value_counts(dropna = False)

frequency_flag
Frequent Customer        22790523
Regular customer          6927608
Non_frequent_customer     2686728
Name: count, dtype: int64

NaN values should mean that there are 5 customers who have only bought once.

In [20]:
ords_prods_merge[['user_id','days_since_prior_order', 'Customer_frequency', 'frequency_flag']].head(100)

    user_id  days_since_prior_order  Customer_frequency         frequency_flag
0       138                     3.0                 8.0      Frequent Customer
1       138                    20.0                 8.0      Frequent Customer
2       709                     6.0                 7.0      Frequent Customer
3       764                     7.0                 9.0      Frequent Customer
4       764                     9.0                 9.0      Frequent Customer
5       777                    26.0                11.0       Regular customer
6       825                    30.0                19.0       Regular customer
7       910                    30.0                 6.0      Frequent Customer
8      1052                    19.0                 9.5      Frequent Customer
9      1052                    15.0                 9.5      Frequent Customer
10     1379                     7.0                20.0       Regular customer
11     1480                     7.0                 7.0      Frequent Customer
12     1480                     7.0                 7.0      Frequent Customer
13     1480                    12.0                 7.0      Frequent Customer
14     1494                     2.0                 7.0      Frequent Customer
15     1494                     6.0                 7.0      Frequent Customer
16     1494                    10.0                 7.0      Frequent Customer
17     1540                     7.0                 7.0      Frequent Customer
18     1540                     6.0                 7.0      Frequent Customer
19     1540                    14.0                 7.0      Frequent Customer
20     1540                     8.0                 7.0      Frequent Customer
21     1540                     6.0                 7.0      Frequent Customer
22     1540                    28.0                 7.0      Frequent Customer
23     1540                     7.0                 7.0      Frequent Customer
24     1540                     7.0                 7.0      Frequent Customer
25     1540                     0.0                 7.0      Frequent Customer
26     1540                     7.0                 7.0      Frequent Customer
27     1540                     7.0                 7.0      Frequent Customer
28     1540                     7.0                 7.0      Frequent Customer
29     1540                     7.0                 7.0      Frequent Customer
30     1540                     3.0                 7.0      Frequent Customer
31     1540                    16.0                 7.0      Frequent Customer
32     1540                     5.0                 7.0      Frequent Customer
33     1540                     6.0                 7.0      Frequent Customer
34     1598                     7.0                 6.0      Frequent Customer
35     1598                    21.0                 6.0      Frequent Customer
36     1598                     2.0                 6.0      Frequent Customer
37     1647                     7.0                25.0  Non_frequent_customer
38     1647                    18.0                25.0  Non_frequent_customer
39     1647                     8.0                25.0  Non_frequent_customer
40     1647                    30.0                25.0  Non_frequent_customer
41     1647                    25.0                25.0  Non_frequent_customer
42     2833                     7.0                 7.0      Frequent Customer
43     2850                     9.0                 7.0      Frequent Customer
44     2857                    10.0                10.0      Frequent Customer
45     3010                     7.0                 7.0      Frequent Customer
46     3029                     7.0                28.0  Non_frequent_customer
47     3395                    30.0                18.0       Regular customer
48     3904                     7.0                15.0       Regular customer
49     4006                     7.0                 7.0      Frequent Customer
50     4006                     7.0                 7.0      Frequent Customer
51     4006                     7.0                 7.0      Frequent Customer
52     4006                     5.0                 7.0      Frequent Customer
53     4006                     4.0                 7.0      Frequent Customer
54     4122                     8.0                 7.0      Frequent Customer
55     4141                    30.0                30.0  Non_frequent_customer
56     4343                     7.0                15.0       Regular customer
57     4553                    29.0                30.0  Non_frequent_customer
58     4845                    12.0                17.0       Regular customer
59     6866                     7.0                30.0  Non_frequent_customer
60     7275                     4.0                12.0       Regular customer
61     7669                     5.0                 5.0      Frequent Customer
62     7669                     5.0                 5.0      Frequent Customer
63     7669                    13.0                 5.0      Frequent Customer
64     7981                    10.0                 7.0      Frequent Customer
65     7981                     6.0                 7.0      Frequent Customer
66     7981                     9.0                 7.0      Frequent Customer
67     7981                     6.0                 7.0      Frequent Customer
68     7981                     8.0                 7.0      Frequent Customer
69     8703                     1.0                 1.0      Frequent Customer
70     8723                     7.0                 6.0      Frequent Customer
71     8735                    21.0                24.0  Non_frequent_customer
72     9293                    30.0                30.0  Non_frequent_customer
73     9293                    30.0                30.0  Non_frequent_customer
74     9467                     7.0                24.0  Non_frequent_customer
75     9694                    30.0                10.0      Frequent Customer
76     9694                     8.0                10.0      Frequent Customer
77     9694                     7.0                10.0      Frequent Customer
78     9694                    14.0                10.0      Frequent Customer
79     9694                    28.0                10.0      Frequent Customer
80     9694                    16.0                10.0      Frequent Customer
81     9694                     1.0                10.0      Frequent Customer
82     9694                    14.0                10.0      Frequent Customer
83     9694                     7.0                10.0      Frequent Customer
84     9694                     8.0                10.0      Frequent Customer
85     9694                    16.0                10.0      Frequent Customer
86     9848                     8.0                11.0       Regular customer
87    10113                    14.0                12.0       Regular customer
88    10315                     7.0                10.0      Frequent Customer
89    10479                     8.0                14.0       Regular customer
90    10708                    14.0                14.0       Regular customer
91    10708                    14.0                14.0       Regular customer
92    10789                    10.0                 7.0      Frequent Customer
93    10789                    14.0                 7.0      Frequent Customer
94    10789                     4.0                 7.0      Frequent Customer
95    10831                    23.0                23.0  Non_frequent_customer
96    11119                    30.0                13.0       Regular customer
97    11186                     2.0                 6.5      Frequent Customer
98    11243                     0.0                 6.0      Frequent Customer
99    11448                     3.0                14.0       Regular customer

# Export Dataframe

In [21]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'aggregated_ords_prods_merge.pkl'))